# Generated by Django 2.2.2 on 2019-06-28 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojinha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bolo',
            name='cobertura',
        ),
        migrations.RemoveField(
            model_name='bolo',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='bolo',
            name='peso',
        ),
        migrations.RemoveField(
            model_name='bolo',
            name='recheio',
        ),
        migrations.RemoveField(
            model_name='bolo',
            name='sabor',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='pagamento',
            field=models.CharField(choices=[('av', 'avista'), ('p2', 'Parcelado em 2 vezes'), ('p3', 'Parcelado em 3 vezes')], default='av', max_length=2),
        ),
    ]
